# -*- coding: utf-8 -*-
"""
/***************************************************************************
 getwktDialog
                                 A QGIS plugin
 This plugin displays the selected features' WKT representation.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-03-13
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Paul Skeen
        email                : paulskeen@spatialecology.com.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os

from PyQt6 import uic
from PyQt6 import QtWidgets
from PyQt6.QtWidgets import QApplication
from PyQt6.QtGui import QKeySequence
from PyQt6.QtCore import Qt
from qgis.core import Qgis
from qgis.utils import iface

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'getwkt_dialog_base.ui'))

class getwktDialog(QtWidgets.QDialog, FORM_CLASS):
    """Get dialog class"""
    def __init__(self, parent=None):
        """Constructor."""
        super(getwktDialog, self).__init__(parent)
        self.setupUi(self)
        
        # Setup signals
        self.pushButton.clicked.connect(self.handleHide)
        self.copyButton.clicked.connect(self.copyAndHide)
        
        # Setup keyboard shortcuts
        self.copyButton.setShortcut(QKeySequence("Ctrl+C"))
        self.pushButton.setShortcut(QKeySequence("Escape"))

    def handleHide(self):
        """Hide handle"""
        self.hide()

    def copyAndHide(self):
        """Copy the WKT content and close"""
        clipboard = QApplication.clipboard()
        wkt_text = self.wktTextEdit.toPlainText()
        if "ERROR" in wkt_text:
            iface.messageBar().pushMessage("Get WKT", "There is no WKT to copy!", level=Qgis.MessageLevel.Warning, duration=5)
            return
        clipboard.setText(wkt_text)
        iface.messageBar().pushMessage("Get WKT", "WKT copied to clipboard", level=Qgis.MessageLevel.Info, duration=5)
        # Auto-select all text for visual feedback
        self.wktTextEdit.selectAll()
        self.handleHide()
